name: CI
on: [push, pull_request]

jobs:
  send-api:
    name: Send API
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Send API message
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_EMAIL: ${{ secrets.PRIVATE_EMAIL }}
          PRIVATE_NAME: ${{ secrets.PRIVATE_NAME }}
          ACTION_RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: python3 main.py
